#!/bin/bash

# Color code variables
red="\e[0;91m"
blue="\e[0;94m"
expand_bg="\e[K"
blue_bg="\e[0;104m${expand_bg}"
red_bg="\e[0;101m${expand_bg}"
green_bg="\e[0;102m${expand_bg}"
green="\e[0;92m"
white="\e[0;97m"
bold="\e[1m"
uline="\e[4m"
reset="\e[0m"
cyan="\e[0;96m"
red_bold="\e[1;91m"
cyan_bold="\e[1;96m"
white_bold="\e[1;37m"

# Dependency check function
require() {
    command -v "$1" > /dev/null 2>&1 || {
        echo "$2 is not installed on your system. Please install $2."
        exit 1
    }
}

require fastfetch "Fastfetch"
require wget "Wget"
require dialog "Dialog"

# Install config base
install_config() {
    local config_url="$1"
    local config_filename="$2"
    local config_path="$3"
    mkdir -p "$(dirname "$config_path")"
    if wget -qO "$HOME/$config_filename" "$config_url"; then
        mv "$HOME/$config_filename" "$config_path"
    else
        fastfetch --gen-config > /dev/null 2>&1
    fi
    clear
    fastfetch -c "$config_path"
    echo
    echo '---------------------------------------------------------------'
    echo
    echo -e "${white_bold}Thanks for using ${red}CLI${cyan}Fetch${white_bold}!${reset}"
    echo
    echo '---------------------------------------------------------------'
    echo
    exit 0
}

# Dialog for welcome message
dialog --title "CLIFetch" --msgbox "Welcome to CLIFetch Created by Daktoo on Github" 8 30

dialog --title "CLIFetch" --yesno "Would you like to install and use the latest config for CLIs?" 0 0
if [ $? -eq 0 ]; then
    install_config "https://raw.githubusercontent.com/Dakota7789/CLIFetch/refs/heads/main/config-cli.jsonc" "config-cli.jsonc" "$HOME/.config/fastfetch/config-cli.jsonc"
fi

dialog --title "CLIFetch" --yesno "Would you like to install and use the latest config for DE/WMs?" 0 0
if [ $? -eq 0 ]; then
    install_config "https://raw.githubusercontent.com/Dakota7789/CLIFetch/refs/heads/main/config-dewm.jsonc" "config-dewm.jsonc" "$HOME/.config/fastfetch/config-dewm.jsonc"
fi

exit 0
