#!/bin/bash

# Welcome message
echo ' '
echo '---------------------------------------------------------------'
echo ' '
echo -e '\033[0mWelcome to \033[31mCLI\033[36mFetch\033[0m!'
echo 'Created by Dakota7789 on GitHub'
echo ' '
echo '---------------------------------------------------------------'
echo ' '
sleep 1

read -p "Would you like to install the latest config? [Y/n] " prompt
if [[ $prompt == "n" || $prompt == "N" || $prompt == "no" || $prompt == "No" ]]
then	
    fastfetch -c ~/.config/fastfetch/config-cli.jsonc
else
    echo ' ' && echo '---------------------------------------------------------------' && echo ' ' && echo 'Installing config...' && echo ' ' && echo '---------------------------------------------------------------' && echo ' ' && cd ~ && wget https://raw.githubusercontent.com/Dakota7789/CLIFetch/refs/heads/main/config-cli.jsonc > /dev/null 2>&1 && mv ~/config-cli.jsonc ~/.config/fastfetch/config-cli.jsonc > /dev/null 2>&1 || fastfetch --gen-config > /dev/null 2>&1 && mv ~/config-cli.jsonc ~/.config/fastfetch/config-cli.jsonc > /dev/null 2>&1 || fastfetch -c ~/.config/fastfetch/config-cli.jsonc
fi

sleep 0.2
echo ' '
echo '---------------------------------------------------------------'
echo ' '
echo -e 'Thanks for using \033[31mCLI\033[36mFetch\033[0m!'
echo ' '
echo '---------------------------------------------------------------'
echo ' '
